name: way
description: WAY - le task cambiano peso a seconda dell'ambiente in cui ti trovi.
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  material_symbols_icons: ^4.2960.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
